.

diff --git a/.github/workflows/analyze.yaml b/.github/workflows/analyze.yaml
--- a/.github/workflows/analyze.yaml
+++ b/.github/workflows/analyze.yaml
@@ -12,10 +12,15 @@ jobs:
     container:
       image:  dart:stable
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - run: dart --version
       - run: dart pub get && (cd example && dart pub get)
       - run: dart analyze --fatal-infos
       - run: dart --enable-asserts tool/prepare_submit.dart
       - name: "check for uncommitted changes"
-        run: git diff --exit-code --stat -- .
+        run: |
+          git diff --exit-code --stat -- . \
+          || (echo "##[error] found changed files after build. please run 'dart tool/prepare_submit.dart'" \
+                   "and check in all changes" \
+              && exit 1)
+        shell: bash
